services:
  catalogdb:
    image: postgres:17

  basketdb:
    image: postgres:17

  distribuitedcache:
    image: redis:latest

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  catalog.api:
    image: eshop/catalog.api:latest
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: eshop/basket.api:latest
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

  discount.grpc:
    image: eshop/discount.grpc:latest
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  sqlite_discount:
  mssql_order:
